main-panel:
  size:
    x: 400
    y: 300

date-panel:
  position:
    x: 0
    y: 0
  size: 
    x: 400
    y: 30
  font:
    font: 'Roboto-Medium.ttf'
    font-size: 15
  
current-panel:
  icon-panel:
    position: 
      x: 0
      y: 30
    size: 
      x: 90
      y: 95
    icon-position: 
      x: 10
      y: 35

  size: 
    x: 280
    y: 95
  icon:
    position: 
      x: 10
      y: 35
  condition-panel:
    position: 
      x: 90
      y: 30
    size: 
      x: 190
      y: 30
    temp:
      font: 'Roboto-Medium.ttf'
      font-size: 35
      position: 
        y: 35
    feels-like:
      font: 'Roboto-Medium.ttf'
      font-size: 11
      position: 
        y: 70
    condition:
      font: 'Roboto-Medium.ttf'
      font-size: 15
      position: 
        y: 85
    humidity: 
      font: 'Roboto-Medium.ttf'
      font-size: 11
      position: 
        y: 105
    wind: 
      font: 'Roboto-Medium.ttf'
      font-size: 11
      position: 
        y: 105



sensor-panel:

daily-panel:

hourly-panel:
  