baseEndpoint: "http://localhost:3000"
endpoints:
    web:
        - subscribe: '/web/subscribe'
        - full: '/web/getFull'
        - currently: '/web/getCurrently'
        - minutely: '/web/getMinutely'
        - hourly: '/web/getHourly'
        - daily:  '/web/getDaily'
        - alerts: '/web/getAlerts'
options:
    - location:
        latitude: <latitude>
        longitude: <longitude>